#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#==============================================================================
# Zookeeper
#==============================================================================

# Zookeeper connection string (see zookeeper docs for details).
# This is a comma separated host:port pairs, each corresponding to a zk
# server. e.g. "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002".
# You can also append an optional chroot string to the urls to specify the
# root directory for all Fluss znodes.
zookeeper.address: xxx:2181
zookeeper.path.root: /fluss-log-bench-new

#==============================================================================
# Common
#==============================================================================

# THe default bucket number to be used when creating tables if no bucket number
# is specified for the table.
default.bucket.number: 3

# The default replication factor to be used when creating tables if no replication
# factor is specified for the table.
default.replication.factor: 3

# The local data directory to be used for Fluss to storing kv and log data.
data.dir: /mnt/fluss-log-bench

# The remote data directory to be used for Fluss. Now, it is only used for storing
# kv snapshot data. Expected be set to a remote location like: oss://bucket/path for oss
# filesystem or hdfs://namenode:port/path for hdfs filesystem
remote.data.dir: oss://fluss-oss-test/fluss-kv-bench
kv.rocksdb.write-batch-size: 128mb

log.replica.fetcher-number: 8
netty.server.num-network-threads: 8
netty.client.num-network-threads: 8
log.fetch.max-bytes-for-bucket: 10mb
log.fetch.max-bytes: 16mb

#==============================================================================
# Coordinator Server
#==============================================================================

# The external address of the host on which the Coordinator Server runs and
# can be reached by the Tablet Servers and any clients which want to connect.
coordinator.host: fluss-new-server1

# The RPC port where the Coordinator Server is reachable.
coordinator.port: 9123

#==============================================================================
# Tablet Server
#==============================================================================

# The external address of the host on which the Tablet Server runs and
# can be reached by the Coordinator Server and any clients which want to connect.
tablet-server.host: fluss-new-server1

# The id of the tablet server to be run, must be set and should be different
# when running multiple tablet servers.
tablet-server.id: 0

#==============================================================================
# OSS FileSystem
#==============================================================================

# The configuration for oss filesystem when using oss as the remote data directory
# fs.oss.endpoint: xxx
# fs.oss.accessKeyId: xxx
# fs.oss.accessKeySecret: xxx
fs.oss.endpoint: oss-cn-hangzhou-internal.aliyuncs.com
fs.oss.accessKeyId: xxx
fs.oss.accessKeySecret: xxx
fs.oss.sts.endpoint: sts.cn-hangzhou.aliyuncs.com
fs.oss.roleArn: xxx